### ISSUE TITLE
BertForSequenceClassfication加载mbert参数与Transformers的对齐

### ISSUE THREAD

**Issue by HYuCui** [lvyufeng/Cybertron#7]
您好，我们在进行mindspore迁移时想要使用到cybertron库的BertForSequenceClassfication这个类，我们想要通过这个类加载mbert的模型，事实上我们在正常加载mbert时会提示最后的分类层的权重和偏置没有被加载(uncased也是一样的情况)

![20221209181241](https://user-images.githubusercontent.com/120175549/206679119-fff30e51-7ab4-4d8e-b2b7-cca9c7c39c33.png)

当我们选择加载bert的时候会出现模型无法加载的情况

![0](https://user-images.githubusercontent.com/120175549/206679468-3c81ab95-6fda-4583-bd02-74c4afce537e.jpg)

事实上，在我们加载mbert的时候，我们发现除了最后一层分类层以外其他权重都对齐的很好，于是我们有尝试手动将最后一层的参数由transformers转换到cybertron从而保证初始参数一致，但是即便如此，在我们选择使用同样的输入对加载了mbert的BertForSequenceClassfication模型进行分类测试的时候，我们发现transformers与cybertron的模型输出结果依旧相差很大，我想要询问一下在模型的初始参数一致的情况下，结构类似（我观察了一下都是embedding+encoder+pooler），输入一样的情况下，分类的结果哪怕不完全相同，不应该很接近吗

**Comment by lvyufeng** [comment]
麻烦把报错截图截全一下

**Comment by HYuCui** [comment]
[WARNING] ME(151096:90652,MainProcess):2022-12-09-18:12:17.300.986 [mindspore\train\serialization.py:709] For 'load_param_into_net', 2 parameters in the 'net' are not loaded, because they are not in the 'parameter_dict', please check whether the network structure is consistent when training and loading checkpoint.
[WARNING] ME(151096:90652,MainProcess):2022-12-09-18:12:17.300.986 [mindspore\train\serialization.py:714] classifier.weight is not loaded.
[WARNING] ME(151096:90652,MainProcess):2022-12-09-18:12:17.300.986 [mindspore\train\serialization.py:714] classifier.bias is not loaded.
这个是加载mbert时最后一层分类未加载

[CRITICAL] ME(135884:152028,MainProcess):2022-12-09-19:28:42.206.046 [mindspore\train\serialization.py:109] Failed to combine the net and the parameters for param bert.embeddings.word_embeddings.embedding_table.
这个是加载bert时的报错
以上为使用BertForSequenceClassification加载预训练模型出现的问题

**Comment by HYuCui** [comment]
您好，我们主要使用的是mbert的加载，麻烦您看一下我上述mbert加载的语法有问题吗，为什么最后一层会没被加载上，其实没被加载上影响也不是很大，我们可以手动转transformers将最后一层加载到cybertron上，但是问题的关键是即便我们手动加载了 ，在保证两边相同的输入的情况下，从encoder_output开始结果就有了很大差异，我们同时对比了最后的分类结果，也具有很大的差异性。

**Comment by lvyufeng** [comment]
好的，我再看一下

**Comment by lvyufeng** [comment]
mbert的huggingface链接发我一下吧

**Comment by HYuCui** [comment]
![20221211105708](https://user-images.githubusercontent.com/120175549/206884201-7aade6fd-be1d-457d-a2d0-562520e6a32e.png)
mbert的加载是通过上面这一句话直接实现的
![20221211105850](https://user-images.githubusercontent.com/120175549/206884248-51635dbb-24b6-4715-b2ff-206c777a52a4.png)

**Comment by Vincent34** [comment]
供参考：

不清楚huggingface的bert权重是怎么组织的，但是原始tensorflow的bert权重中Dense权重排列和MindSpore是相反的，需要做一个转置。
https://github.com/mindspore-ai/models/blob/master/official/nlp/Bert/scripts/ms2tf/ms_and_tf_checkpoint_transfer_tools.py

**Comment by lvyufeng** [comment]
你用的什么版本，具体代码片段都附上吧，现在这个描述不清楚，我写了个ut测试BertForSequenceClassification加载不同的ckpt，都没有任何问题。不同的MindSpore版本也都试了，我怀疑是你使用方式的问题。

**Comment by backwoof** [comment]
您好。确认过模型参数加载正确的前提下，在进行英语分类训练的时候与pytorch版本对比有2个问题：1、相同的输入进入模型，pytorch版本的速度比mindspore版本的要快很多；2、训练损失不下降，只在训练初期下降一点（使用的是交叉熵损失，更换CNN模型进行分类没发现问题），而pytorch的精度提升比较快。请问这些是正常差异吗，如果不是，那该如何解决呢？

**Comment by backwoof** [comment]
![微信图片_20221216165329](https://user-images.githubusercontent.com/86396720/208061399-b2570920-2691-4a05-88af-448dc2552cad.jpg)

**Comment by backwoof** [comment]
![微信图片_202212161653291](https://user-images.githubusercontent.com/86396720/208061413-00cfe20c-c3a5-4612-8de5-320cb7c9349c.jpg)

**Comment by backwoof** [comment]
![微信图片_202212161653292](https://user-images.githubusercontent.com/86396720/208061429-9c3075fc-8bc8-4d94-88a2-cec6f61b1f71.jpg)

**Comment by lvyufeng** [comment]
直接复制代码块。。。。截图我还得手动敲。。。。

代码块前后加上```，就可以显示为代码块

**Comment by lvyufeng** [comment]
> 

1. 用nn.CrossEntropyLoss
2. 用函数式写法

**Comment by HYuCui** [comment]
您好，能请问一下有在下游任务句子分类上成功微调的bert模型的例子吗，我们想要参考一下。

**Comment by lvyufeng** [comment]
可以参考：https://github.com/cqunlp/bert
